Closes #175 - Switch to get_admiral_option() for subject_keys
pharmaverse/admiralonco pull request #186
Opened 2022-11-09 19:42 UTC by zdz2101

Please add "Closes #<issue number>" to the title of the pull request. Then the
issue is closed automatically once it is merged to `main`.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiralonco/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

The following line requests to update the man pages by the "Man Pages" workflow.

/roxygenize

2022-11-10 09:36 UTC, rossfarrugia commented
@zdz2101 please update the NEWS.md file. @bundfussr hope you're ok to review this PR?

2022-11-10 11:48 UTC, bundfussr requested changes

2022-11-10 11:48 UTC, bundfussr commented on R/admiralonco-package.R
> +#'   params restrict_derivation yn_to_numeric get_admiral_option set_admiral_options
Could you add the new functions such that all the functions are in alphabetic order?

2022-11-30 16:50 UTC, bundfussr commented
@zdz2101 , could you fix the styler check? The R-CMD checks should pass when re-running as they were caused by an issue in admiral.

2022-11-30 18:21 UTC, zdz2101 commented
@bundfussr Made the appropriate styler edits but now running into NAMESPACE issues because of the removal of `set_dataset()` from `admiraldev` which also impacts `signal_crpr()`/`get_crpr_dataset()` under `R/check_crpr.R` This may also be related to perhaps implementing an `admiralonco_environment` object to set up the object `crpr`.

2022-12-01 12:24 UTC, bundfussr commented
@zdz2101 , yes, only the failing "Man Pages" check is not related to https://github.com/pharmaverse/admiralonco/pull/192.

2022-12-01 16:09 UTC, merged