Closes #187 Update vignettes: add BICR alongside IRF
pharmaverse/admiralonco pull request #188
Opened 2022-11-10 18:55 UTC by kaz462

Please add "Closes #<issue number>" to the title of the pull request. Then the
issue is closed automatically once it is merged to `main`.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiralonco/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

The following line requests to update the man pages by the "Man Pages" workflow.

/roxygenize

2022-11-11 10:58 UTC, rossfarrugia commented
@kaz462 thanks for another contribution! Heads up for future that you dont need to add the PR to the project board on the right hand side, we only do this for the issues (and each of them get linked to the PR anyway).

@HinalPat i added you as reviewer but feel free to delegate.

2022-11-11 11:01 UTC, rossfarrugia commented
p.s. if the spellcheck auto-check fails it will likely be because you just need to add `BICR` to `inst/WORDLIST` file. Sometimes it oddly let's things like this through though!

2022-11-11 20:06 UTC, kaz462 commented
@HinalPat Thanks for assigning me the issue!
@rossfarrugia Good to know that we only need issues in the project board, no need to add PR. 
Thanks for your information about the spellcheck and potential words to be added in `inst/WORDLIST` if it fails - good learnings for me!

2022-12-05 10:34 UTC, bundfussr requested changes
Thanks @kaz462 , looks almost good to me.
Only one place where "BICR" should be added.
If you add it and fix the merge conflicts, we can merge the PR.

2022-12-05 10:34 UTC, bundfussr commented on vignettes/adrs.Rmd
>  Review Facility instead of investigator. For this you would just need to replace the first steps with selecting the required
I would replace "the Independent Review Facility" with "IRF/BICR".

2022-12-06 11:19 UTC, bundfussr approved these changes

2022-12-06 11:53 UTC, merged